
name: OpenCue Release Pipeline

on:
  push:
    tags:
      - "v*"

jobs:
  deploy_proto:
    environment: deploy
    runs-on: ubuntu-22.04
    name: Deploy opencue_proto
    container: python:3.7
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: Mark repository as safe (Fix for https://github.com/actions/checkout/issues/1048)
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine build

      - name: Build opencue_proto package
        run: python -m build ./proto

      - name: Upload to pypi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_KEY }}
        run: |
          python3 -m twine upload --repository testpypi proto/dist/* --verbose
